-- Coffee & Me daily story library.
-- Designed to scale to 1,000+ editorial stories while keeping one stable story per user/day.

CREATE TABLE IF NOT EXISTS coffee_stories (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  kicker TEXT NOT NULL DEFAULT 'داستان امروز',
  excerpt TEXT NOT NULL DEFAULT '',
  story_text TEXT NOT NULL,
  lesson TEXT NOT NULL DEFAULT '',
  story_type TEXT NOT NULL DEFAULT 'literary'
    CHECK (story_type IN ('historical','cultural','origin','people','invention','literary')),
  era TEXT NOT NULL DEFAULT '',
  place TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  source_label TEXT NOT NULL DEFAULT '',
  source_url TEXT NOT NULL DEFAULT '',
  is_factual INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','published','archived')),
  featured INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_coffee_stories_status
  ON coffee_stories (status, featured, updated_at);

CREATE TABLE IF NOT EXISTS coffee_story_assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  anonymous_id TEXT NOT NULL,
  local_date TEXT NOT NULL,
  story_id TEXT NOT NULL,
  assigned_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (story_id) REFERENCES coffee_stories(id) ON DELETE CASCADE,
  UNIQUE (anonymous_id, local_date)
);

CREATE INDEX IF NOT EXISTS idx_story_assignments_user
  ON coffee_story_assignments (anonymous_id, assigned_at DESC);

CREATE INDEX IF NOT EXISTS idx_story_assignments_story
  ON coffee_story_assignments (story_id, assigned_at DESC);

INSERT OR IGNORE INTO coffee_stories
(id, slug, title, kicker, excerpt, story_text, lesson, story_type, era, place, image_url, source_label, source_url, is_factual, status, featured)
VALUES
(
  'story-melitta-1908',
  'a-piece-of-paper-changed-coffee',
  'یک تکه کاغذ که قهوه را عوض کرد',
  'داستان امروز · اختراع',
  'گاهی یک مشکل کوچک روی میز آشپزخانه، شروع یک تغییر بزرگ می‌شود.',
  'سال ۱۹۰۸، ملیتا بنتز از ته‌نشین شدن پودر قهوه و تلخی فنجانش خسته شده بود. به‌جای پذیرفتن وضع موجود، سراغ یک آزمایش ساده رفت: روی یک ظرف برنجی سوراخ‌هایی ایجاد کرد و از کاغذ جاذب به‌عنوان فیلتر استفاده کرد. همین تجربه خانگی به ایده فیلتر کاغذی قهوه تبدیل شد و بعدها روش‌های پوراور را برای میلیون‌ها نفر ساده‌تر کرد. داستانش بیش از آنکه درباره یک ابزار باشد، درباره دیدن یک اصطکاک روزمره و جدی گرفتن آن است.',
  'اگر چیزی هر روز آزارت می‌دهد، شاید همان چیز ارزش این را دارد که یک بار متفاوت امتحانش کنی.',
  'invention',
  '۱۹۰۸',
  'درسدن، آلمان',
  '/media/brew-filter-human-v2',
  'Melitta · The Melitta Story',
  'https://www.melitta.com/en/About-Us/Our_Passion_through_the_years',
  1,
  'published',
  1
),
(
  'story-espresso-speed',
  'espresso-was-born-from-waiting',
  'وقتی پنج دقیقه انتظار زیادی بود',
  'داستان امروز · تاریخ اسپرسو',
  'بعضی اختراع‌ها از یک سؤال ساده شروع می‌شوند: چطور سریع‌ترش کنیم؟',
  'در کافه‌های اروپای قرن نوزدهم، دم‌آوری قهوه زمان می‌برد. مخترعان شروع کردند به استفاده از فشار و بخار تا زمان انتظار را کوتاه کنند. آنجلو موریوندو در ۱۸۸۴ دستگاهی بخارمحور ثبت کرد و در آغاز قرن بیستم لوئیجی بزرا و سپس دزیدریو پاوونی مسیر را به سمت قهوه تک‌فنجانی و چیزی که امروز اسپرسو می‌شناسیم جلو بردند. چیزی که ابتدا مسئله سرعت بود، کم‌کم تبدیل شد به فرهنگی کامل از دقت، فشار و تکرارپذیری.',
  'خیلی وقت‌ها کیفیت از دل محدودیت بیرون می‌آید؛ اگر مسئله را دقیق تعریف کنی، محدودیت می‌تواند موتور طراحی شود.',
  'historical',
  '۱۸۸۴ تا ۱۹۰۶',
  'ایتالیا',
  '/media/brew-espresso-human-v2',
  'Smithsonian Magazine · The Long History of the Espresso Machine',
  'https://www.smithsonianmag.com/arts-culture/the-long-history-of-the-espresso-machine-126012814/',
  1,
  'published',
  1
),
(
  'story-portafilter',
  'the-handle-that-made-a-shot-personal',
  'وقتی قهوه از دیگ بزرگ جدا شد',
  'داستان امروز · طراحی',
  'گاهی یک قطعه کوچک، تجربه آدم‌ها را از «جمعی» به «شخصی» تبدیل می‌کند.',
  'ماشین‌های اولیه قهوه تحت فشار بیشتر برای حجم بالا ساخته شده بودند. توسعه پورتافیلتر و هدهای دم‌آوری تک‌فنجانی در نسل‌های بعدی دستگاه‌های اسپرسو، امکان داد هر فنجان جداگانه آماده شود. این تغییر کوچک در ظاهر، رابطه باریستا با یک شات را عوض کرد: حالا آسیاب، مقدار قهوه و اجرای همان یک فنجان اهمیت پیدا می‌کرد.',
  'وقتی تجربه را به واحد کوچک‌تری می‌شکنی، امکان توجه و شخصی‌سازی بیشتر می‌شود.',
  'historical',
  'اوایل قرن بیستم',
  'ایتالیا',
  '/media/espresso',
  'Smithsonian Magazine · The Long History of the Espresso Machine',
  'https://www.smithsonianmag.com/arts-culture/the-long-history-of-the-espresso-machine-126012814/',
  1,
  'published',
  0
),
(
  'story-crema',
  'crema-needed-a-new-name',
  'کفی که اول عجیب به نظر می‌رسید',
  'داستان امروز · تغییر نگاه',
  'چیز تازه همیشه در نگاه اول «بهتر» دیده نمی‌شود.',
  'با توسعه دستگاه‌های اهرمی پرفشار پس از جنگ جهانی دوم، لایه طلایی‌رنگی روی اسپرسو پدیدار شد که امروز آن را کرما می‌شناسیم. روایت‌های تاریخی صنعت می‌گویند این ظاهر تازه ابتدا برای بعضی مشتری‌ها ناآشنا بود و باید معنای تازه‌ای برایش ساخته می‌شد. چند دهه بعد، همان نشانه غریب به یکی از نمادهای اسپرسو تبدیل شد.',
  'گاهی مسئله کیفیت نیست؛ مسئله این است که آدم‌ها هنوز زبان فهمیدن چیز تازه را پیدا نکرده‌اند.',
  'historical',
  'پس از جنگ جهانی دوم',
  'ایتالیا',
  '/media/espresso',
  'Smithsonian Magazine · The Long History of the Espresso Machine',
  'https://www.smithsonianmag.com/arts-culture/the-long-history-of-the-espresso-machine-126012814/',
  1,
  'published',
  0
),
(
  'story-four-ms',
  'four-ms-of-espresso',
  'ماشین خوب کافی نیست',
  'داستان امروز · چهار M',
  'در اسپرسو، ابزار فقط یکی از چهار ضلع ماجراست.',
  'در سنت ایتالیایی اسپرسو از چهار M حرف می‌زنند: Macchina برای ماشین، Macinazione برای آسیاب، Miscela برای ترکیب قهوه و Mano برای دست و مهارت باریستا. این چهارگانه یادآوری می‌کند که خریدن ابزار بهتر، به‌تنهایی تضمین‌کننده فنجان بهتر نیست؛ ماده، تنظیم و اجرای آدم هم در نتیجه شریک‌اند.',
  'ابزار می‌تواند توان تو را بیشتر کند، اما جای توجه و مهارت را نمی‌گیرد.',
  'cultural',
  'قرن بیستم',
  'ایتالیا',
  '/media/brew-espresso-human-v2',
  'Smithsonian Magazine · The Long History of the Espresso Machine',
  'https://www.smithsonianmag.com/arts-culture/the-long-history-of-the-espresso-machine-126012814/',
  1,
  'published',
  0
),
(
  'story-clean-cup',
  'clean-cup-small-frustration',
  'فنجان تمیز از یک کلافگی شروع شد',
  'داستان امروز · حل مسئله',
  'نوآوری همیشه از آزمایشگاه شروع نمی‌شود.',
  'ملیتا بنتز در خانه با یک مشکل کاملاً معمولی روبه‌رو بود: تفاله‌ای که وارد فنجان می‌شد و طعمی که آن‌طور که می‌خواست تمیز نبود. ایده فیلتر کاغذی از همین تجربه شخصی شکل گرفت. نکته مهم داستان این نیست که همه باید مخترع شوند؛ این است که ناراحتی‌های کوچک روزمره می‌توانند اطلاعات خوبی درباره چیزی که نیاز به تغییر دارد بدهند.',
  'قبل از اینکه به یک مشکل عادت کنی، یک بار از خودت بپرس چرا باید همین‌طور بماند.',
  'people',
  '۱۹۰۸',
  'آلمان',
  '/media/v60',
  'Melitta · The Melitta Story',
  'https://www.melitta.com/en/About-Us/Our_Passion_through_the_years',
  1,
  'published',
  0
),
(
  'story-repeatable-cup',
  'the-cup-you-can-repeat',
  'فنجان خوب اتفاقی نیست',
  'حکایت قهوه‌ای · تکرار',
  'یک فنجان عالی که نتوانی دوباره بسازی، بیشتر شانس است تا مهارت.',
  'فرض کن یک صبح بدون اندازه‌گیری، بدون توجه به آسیاب و بدون یادداشت، بهترین قهوه ماهت را درست می‌کنی. روز بعد می‌خواهی تکرارش کنی و هیچ‌چیز یادت نیست. این حکایت ساده یک فرق مهم را نشان می‌دهد: نتیجه خوب با فرایند خوب یکی نیست. فرایند خوب چیزی است که بتوانی دوباره اجرا و بعد آگاهانه بهترش کنی.',
  'موفقیت واقعی فقط رسیدن نیست؛ توانایی تکرار چیزی است که جواب داده.',
  'literary',
  'امروز',
  'هر آشپزخانه‌ای',
  '/media/brew-v60-human-v2',
  '',
  '',
  0,
  'published',
  0
),
(
  'story-last-bean',
  'the-last-bean-in-the-jar',
  'آخرین دانه ته شیشه',
  'حکایت قهوه‌ای · قدرشناسی',
  'گاهی کمیابی باعث می‌شود چیزی را دقیق‌تر ببینیم.',
  'در یک صبح معمولی، کسی سراغ شیشه قهوه رفت و دید فقط برای یک فنجان دانه مانده. به‌جای عجله، همان یک فنجان را با دقت وزن کرد، آب را آرام ریخت و برای اولین بار بعد از مدت‌ها بدون گوشی نشست و نوشید. قهوه همان قهوه همیشگی بود؛ چیزی که تغییر کرده بود توجه او بود.',
  'خیلی وقت‌ها لذت کم نشده؛ توجه ما کم شده است.',
  'literary',
  'امروز',
  'خانه',
  '/media/me',
  '',
  '',
  0,
  'published',
  0
),
(
  'story-two-cups',
  'two-cups-same-table',
  'دو فنجان روی یک میز',
  'حکایت قهوه‌ای · گفتگو',
  'همه اختلاف‌ها با جواب شروع نمی‌شوند؛ بعضی‌هایشان با نشستن شروع می‌شوند.',
  'دو دوست بعد از مدت‌ها دلخوری در یک کافه نشستند. هیچ‌کدام نمی‌دانست از کجا شروع کند. سفارش قهوه زمان خرید؛ صدای آسیاب، مکث باریستا و چند جرعه اول، سکوت را قابل‌تحمل کرد. گفت‌وگو از خود قهوه شروع شد و بعد به چیزی رسید که ماه‌ها عقب افتاده بود. قهوه مسئله را حل نکرد؛ فقط فضایی ساخت که حرف زدن ممکن شود.',
  'گاهی لازم نیست فوراً راه‌حل داشته باشی؛ اول باید فضایی بسازی که گفت‌وگو در آن ممکن باشد.',
  'literary',
  'امروز',
  'یک کافه',
  '/media/philosophy',
  '',
  '',
  0,
  'published',
  0
),
(
  'story-bitter-cup',
  'the-bitter-cup-that-was-not-bad',
  'فنجان تلخی که بد نبود',
  'حکایت قهوه‌ای · قضاوت',
  'اولین برداشت همیشه دقیق‌ترین برداشت نیست.',
  'کسی یک قهوه تازه امتحان کرد و با اولین جرعه گفت: «تلخه، پس خوب نیست.» چند دقیقه بعد، وقتی فنجان کمی خنک شد، شیرینی و عطرهایی را حس کرد که اول به چشمش نیامده بود. همان فنجان یادآوری کرد که بعضی چیزها برای نشان دادن خودشان کمی زمان می‌خواهند.',
  'قبل از قضاوت نهایی، گاهی فقط چند دقیقه بیشتر فرصت بده.',
  'literary',
  'امروز',
  'هر جا',
  '/media/fix',
  '',
  '',
  0,
  'published',
  0
),
(
  'story-grind-one-step',
  'one-click-at-a-time',
  'فقط یک کلیک',
  'حکایت قهوه‌ای · تغییر',
  'وقتی همه‌چیز را با هم عوض می‌کنی، هیچ‌چیز یاد نمی‌گیری.',
  'یک نفر از فنجانش ناراضی بود و هم‌زمان دما، آسیاب، دوز و زمان را تغییر داد. نتیجه بهتر شد، اما نمی‌دانست چرا. دفعه بعد دوباره همه‌چیز از دست رفت. از آن روز تصمیم گرفت هر بار فقط یک متغیر را تغییر دهد. پیشرفت کندتر به نظر می‌رسید، اما هر فنجان چیزی به او یاد می‌داد.',
  'تغییر کوچک و قابل‌اندازه‌گیری، از تغییر بزرگ و مبهم آموزنده‌تر است.',
  'literary',
  'امروز',
  'کنار آسیاب',
  '/media/fix-grind-medium',
  '',
  '',
  0,
  'published',
  0
),
(
  'story-pour-over-patience',
  'pouring-water-is-not-rushing',
  'آرام ریختن',
  'حکایت قهوه‌ای · صبر',
  'بعضی نتیجه‌ها با فشار بیشتر بهتر نمی‌شوند.',
  'در پوراور، عجله می‌تواند جریان را به‌هم بزند. داستانش شبیه خیلی از کارهای روزمره است: وقتی می‌خواهیم زودتر تمام شود، گاهی کنترل کمتری داریم. ریختن آرام آب روی بستر قهوه یک تمرین کوچک است برای دیدن اینکه سرعت کمتر همیشه به معنی پیشرفت کمتر نیست.',
  'آرام‌تر رفتن، اگر کنترل بیشتری بدهد، می‌تواند سریع‌ترین راه به نتیجه بهتر باشد.',
  'literary',
  'امروز',
  'کنار V60',
  '/media/brew-v60-human-v2',
  '',
  '',
  0,
  'published',
  0
);
